@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah


{
  "make": "Hyundai",
   "model": "i20",
   "year": 2019
   
}


###
@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah




###
GET  {{endpoint}}/6ac60159241cf83c6bee2bac HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ac60159241cf83c6bee2bac HTTP/3.0
content-type: application/json

###

### Valid update – expect 200
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

{
  "make": "Ford",
  "model": "Fiesta",
  "year": 2019
}

### Empty make – expect 400
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

{
  "make": "",
  "model": "Focus"
}

### Year too old – expect 400
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

{
  "make": "BMW",
  "model": "M3",
  "year": 1900
}




### GET all cars - No API key

GET {{endpoint}} HTTP/1.1
content-type: application/json


### GET all cars - With API key

GET {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

