@endpoint = http://localhost:3000/api/v1/cars

###
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Audi",
   "model": "A4"
}


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/sillycarID HTTP/3.0

content-type: application/json


###

DELETE  {{endpoint}}/6ab39e3478e96cf481b20de1 HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

