@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah


{
  "make": "BMW",
   "model": "M5"
}

###
@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah


###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json


###

DELETE  {{endpoint}}/6ab66fadff930eb9e04ca664 HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json




### GET all cars - No API key

GET {{endpoint}} HTTP/1.1
content-type: application/json


### GET all cars - With API key

GET {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

